### ISSUE TITLE
Is there a way to group results?

### ISSUE THREAD

**Issue by Sleon4** [robiningelbrecht/phpunit-pretty-print#10]
I have installed the library because I like the way it shows the output of the tests.

But I have come across something a little uncomfortable, I have many tests and this makes me use scrolling just to see the results.

Isn't there a way for the results to be grouped by class? suites?

![image](https://github.com/robiningelbrecht/phpunit-pretty-print/assets/56183278/ac20571b-f3b5-4787-a252-5cbd5991635c)

**Comment by robiningelbrecht** [comment]
Hi @Sleon4,

You could use the "compact" option.
Just to be clear, this package does not handle the formatting. It only integrates collision with PHPUnit, any formatting is done by Collision.

**Comment by Sleon4** [comment]
Hello @robiningelbrecht , thanks for teaching me, I am new with these libraries. thanks for your contributions
