### ISSUE TITLE
Support for PHPUnit 11.x

### ISSUE THREAD

**Issue by gabrielrbarbosa** [robiningelbrecht/phpunit-pretty-print#7]
Cant updated phpunit/phpunit ^11.0.0 in composer due to fixed version here on composer at ^10.3

**Comment by gabrielrbarbosa** [comment]
@robiningelbrecht 
 - robiningelbrecht/phpunit-pretty-print v1.3.0 requires nunomaduro/collision ^7.8 -> found nunomaduro/collision[v7.8.0, ..., v7.x-dev] but it conflicts with your root composer.json require (^8.0).
 
 nunomaduro/collision supports phpunit 11 only in versions ^8.x

**Comment by robiningelbrecht** [comment]
@gabrielrbarbosa that's weird, I have this on my onw local environment and seems to work:
<img width="363" alt="image" src="https://github.com/robiningelbrecht/phpunit-pretty-print/assets/203894/9e092dd8-3d07-48ed-892e-6feef9aca9e5">

**Comment by robiningelbrecht** [comment]
@gabrielrbarbosa just ran a CI with PHP 8.1, 8.2 and PHPUnit 10.x and 11.x, this is the result:

https://github.com/robiningelbrecht/phpunit-pretty-print/actions/runs/7962726867

All seems good?

Edit: you project probably depends on _nunomaduro/collision_ version 8?

**Comment by gabrielrbarbosa** [comment]
https://github.com/nunomaduro/collision?tab=readme-ov-file#version-compatibility

**Comment by robiningelbrecht** [comment]
@gabrielrbarbosa ok, but my CI says otherwise right? :)
<img width="448" alt="image" src="https://github.com/robiningelbrecht/phpunit-pretty-print/assets/203894/61c23da8-9f3c-44ab-b06f-c53390f28a63">
Not sure what to do...

**Comment by gabrielrbarbosa** [comment]
cant you allow both versions here on composer like '^7.10|^8.0' ? I think that would solve for people that would read his readme and fix to 8.x

**Comment by robiningelbrecht** [comment]
@gabrielrbarbosa that might do the trick yeah. 
Could you verify that this PR fixes your issue? https://github.com/robiningelbrecht/phpunit-pretty-print/pull/9

**Comment by robiningelbrecht** [comment]
@gabrielrbarbosa I could also release a 2.x version so that:
1.x supports PHPUnit 10
2.x supports PHPunit 11

What do you think?

**Comment by gabrielrbarbosa** [comment]
it does install correctly now tested from "robiningelbrecht/phpunit-pretty-print": "dev-test-different-phpunit-versionbs", thanks!

**Comment by robiningelbrecht** [comment]
Going to release new version
